services:
  backend:
    build: ./back_end
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back_end/tms/:/app
    ports:
      - "8000:8000"
    env_file:
      - ./back_end/tms/.env
    depends_on:
      - db

  frontend:
    build: ./front_end/tms
    container_name: vite_frontend
    volumes:
      - ./front_end/tms/:/app:cached
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
    - ./back_end/tms/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: